# hugo.toml - main config entry point
# The bulk of configuration is in config/_default/

baseURL = 'https://todayyohoho.github.io/'
title = '我的博客'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[params]
  copyright = "© 2026 - 我的博客"
